permalink: /:categories/:title.html
url: "http://clhenrick.github.io/jekyll-masonry/"
full_name: "Chris L Henrick"
first_name: "Chris"
last_name: "Henrick"
blog_title: "Clhenrick"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "chrishenrick"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Geo Web Developer, Cartographer, Tinkerer"
twitter: "chrislhenrick"
github: "clhenrick"
linkined_url: ""
highlighter: "pygments"